/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as AuthedWorkflowsRouteImport } from './routes/_authed.workflows'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedJiraRouteImport } from './routes/_authed.jira'
import { Route as AuthedHubRouteImport } from './routes/_authed.hub'
import { Route as AuthedWorkflowsEditorRouteImport } from './routes/_authed.workflows_.editor'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthedWorkflowsRoute = AuthedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJiraRoute = AuthedJiraRouteImport.update({
  id: '/jira',
  path: '/jira',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHubRoute = AuthedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsEditorRoute = AuthedWorkflowsEditorRouteImport.update({
  id: '/workflows_/editor',
  path: '/workflows/editor',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/hub': typeof AuthedHubRoute
  '/jira': typeof AuthedJiraRoute
  '/settings': typeof AuthedSettingsRoute
  '/workflows': typeof AuthedWorkflowsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/workflows/editor': typeof AuthedWorkflowsEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/hub': typeof AuthedHubRoute
  '/jira': typeof AuthedJiraRoute
  '/settings': typeof AuthedSettingsRoute
  '/workflows': typeof AuthedWorkflowsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/workflows/editor': typeof AuthedWorkflowsEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/hub': typeof AuthedHubRoute
  '/_authed/jira': typeof AuthedJiraRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/workflows': typeof AuthedWorkflowsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/_authed/workflows_/editor': typeof AuthedWorkflowsEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/hub'
    | '/jira'
    | '/settings'
    | '/workflows'
    | '/login/callback'
    | '/workflows/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/hub'
    | '/jira'
    | '/settings'
    | '/workflows'
    | '/login/callback'
    | '/workflows/editor'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/hub'
    | '/_authed/jira'
    | '/_authed/settings'
    | '/_authed/workflows'
    | '/login/callback'
    | '/_authed/workflows_/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authed/workflows': {
      id: '/_authed/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthedWorkflowsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jira': {
      id: '/_authed/jira'
      path: '/jira'
      fullPath: '/jira'
      preLoaderRoute: typeof AuthedJiraRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hub': {
      id: '/_authed/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthedHubRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows_/editor': {
      id: '/_authed/workflows_/editor'
      path: '/workflows/editor'
      fullPath: '/workflows/editor'
      preLoaderRoute: typeof AuthedWorkflowsEditorRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedHubRoute: typeof AuthedHubRoute
  AuthedJiraRoute: typeof AuthedJiraRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedWorkflowsRoute: typeof AuthedWorkflowsRoute
  AuthedWorkflowsEditorRoute: typeof AuthedWorkflowsEditorRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHubRoute: AuthedHubRoute,
  AuthedJiraRoute: AuthedJiraRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedWorkflowsRoute: AuthedWorkflowsRoute,
  AuthedWorkflowsEditorRoute: AuthedWorkflowsEditorRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
